services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/home

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    ports:
      - '5432:5432'

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'